### ISSUE TITLE
Marshal to map[string]string

### ISSUE THREAD

**Issue by bradrydzewski** [vrischmann/envconfig#10]
it would be interesting to make this bidirectional. For example, could I generate environment variables from a structure (and return as `map[string]string`):

```Go
v := struct {
  User string
  Pass string
}{ "root", "pa55word" }

envs, err := envconfig.Marshal(&v)
envs, err := envconfig.MarshalPrefix("MYSQL", &v)

// where envs looks like this
map[string]string {
  "MYSQL_USER": "root",
  "MYSQL_PASS": "pa55word",
}
```

**Comment by vrischmann** [comment]
Hi.

Thanks for the suggestion. I can see something like this being useful, especially to export variables to a systemd file for example or whatever.

However, I'm not willing to overly complicate the code to add this feature, because it's a "nice to have" but not something absolutely necessary for the purpose of envconfig, in my opinion.

I'll have to see how I could do it.

**Comment by vrischmann** [comment]
So, it's been a long time. I spent some time thinking about it today, and I'm not going to add this functionality.

Like I said at the time, I'd rather keep the library small and focused on one thing.
